### ISSUE TITLE
Document Vault integration

### ISSUE THREAD

**Issue by mkysel** [nuodb/nuodb-helm-charts#151]
This is a request for a standalone howto document for the Vault integration.

**Comment by vegichan** [comment]
@sivanov-nuodb  do we have a plan for a Github based Vault-integration document?

**Comment by sivanov-nuodb** [comment]
NuoDB Transparent Data Encryption (TDE) and integration with Vault has been documented in https://github.com/nuodb/nuodb-helm-charts/pull/171. 
NuoDB TLS integration using Vault is what left for this issue to be completed.
