### ISSUE TITLE
TLS Custom Key mount does not work in OCP 3.11

### ISSUE THREAD

**Issue by vegichan** [nuodb/nuodb-helm-charts#76]

**Comment by adriansuarez** [comment]
Is this custom key for the Admin or for database processes? Do we ever start database processes with an explicit key because the Admin does not have the CA=true attribute (I see some plumbing in the templates that looks like it enables that)?

**Comment by vegichan** [comment]
This is a helm issue, not a NuoDB issue. You cant specify any custom keys with our current helm charts in OCP 3.11. The charts will not deploy.
